apiVersion: v1
kind: Service
metadata:
  name: backend-helloworld-golang
spec:
  selector:
    app: backend-helloworld-golang
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080

